project5/config/routes.rb
Project4::Application.routes.draw do
    resources :users do
        get :login, on: :collection
        post :post_login, on: :collection
        get :logout, on: :collection
    end
    resources :photos do
        resources :comments
    end

  

end

project5/app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :photo
    belongs_to :user
end

project5/app/models/photo.rb
class Photo < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

project5/app/models/user.rb
require 'securerandom'
require 'digest'

class User < ActiveRecord::Base
    has_many :photos
    has_many :comments
    validates :login, uniqueness: true
    
    def full_name
        first_name + ' '+ last_name
    end
    def password
        @password
    end
    def password=(newpass)
        @password = newpass
        write_attribute(:salt,SecureRandom.hex)
        write_attribute(:password_digest, Digest::SHA2.hexdigest(newpass + salt))
    end
    def password_valid?(pw)
        return password_digest == (Digest::SHA2.hexdigest(pw + salt))
    end
end

project5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

project5/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @photo = Photo.find(params[:photo_id])
        @user = @photo.user
        @comments = @photo.comments
        @title = @user.full_name + " photo: "+@photo.date_time
        @comment = Comment.new
    end
    
    def create
        @photo = Photo.find(params[:photo_id])
        @user = @photo.user
        @comment = Comment.new(comment_params)
        @comment.user = session[:login]
        @comment.date_time = DateTime.now
        @comment.photo = @photo
        if @comment.save
            redirect_to @comment.photo.user
        else
            render 'new'
        end
    end
    
    def index
    end
    
    def show
    end
    
    private
        def comment_params
            params.require(:comment).permit(:photo,:user,:date_time,:comment)
        end
end

project5/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_filter :require_login
    
    def new
        @title = "Upload a new photo"
        @photo = Photo.new
    end
    
    def create
        @photo = Photo.new
        filename = params[:photo][:input_file].original_filename
        @photo.file_name = filename
        @photo.date_time = DateTime.now
        @photo.user = session[:login]
        if @photo.save
            path = Rails.root.join("app","assets","images",filename)
            open(path,"wb") do |file|
                file << params[:photo][:input_file].read
            end
            flash[:notice] = "Photo: "+filename+" successfully uploaded"
            redirect_to @photo.user
        else
            render 'new'
        end
    end
    
    private
    def require_login
        if session[:login].nil?
            flash[:notice] = "You must log in before posting photos."
            redirect_to users_path
        end
    end
end

project5/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @title = "List of Users"
        @users = User.all
    end
    
    def new
        @title = "New User Registration"
        @user = User.new
    end
    
    def create
        @user= User.new(user_params)
        @user.password= params[:user][:password]
        if @user.save
            redirect_to @user
        else
            render 'new'
        end
    end
    
    def show
        @user = User.find(params[:id])
        @title = @user.first_name + " " + @user.last_name + " page"
    end
    
    def login
        @title = "Login"
    end
    
    def post_login
        @user = User.find_by_login(params[:login])
        if @user.nil?
            session[:login_error] = params[:login]    
            redirect_to :back, status: 302
        else
            if @user.password_valid?(params[:password])
                session[:login] = @user
                session[:login_error] = nil    
                redirect_to @user, status: 302
            else
                session[:login_error] = "!password"    
                redirect_to :back, status: 302
            end
        end
    end
    
    def logout
        session[:login] = nil
        redirect_to action: :index, status: 302
    end
    
    private
    def user_params
        params.require(:user).permit(:first_name,:last_name,:login,:password_digest,:salt)
    end
end

project5/app/helpers/application_helper.rb
module ApplicationHelper
end

project5/app/helpers/comments_helper.rb
module CommentsHelper
end

project5/app/helpers/photos_helper.rb
module PhotosHelper
end

project5/app/helpers/users_helper.rb
module UsersHelper
end

project5/app/views/photos/new.html.erb
<h1>Upload a new photo</h1>
<%= form_for @photo do |f| %>

    <% if @photo.errors.any? %>
    <div id="error explanation">
        <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from uploading:</h2>
        <ul>
        <% @photo.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <div><p><%= f.file_field :input_file %></p></div>
    <div><p><%= f.submit %></p></div>
<% end %>

project5/app/views/shared/_photo_and_comments.html.erb
<div>
    <hr /><p>
    <strong> Date uploaded: </strong>
    <%= photo.date_time %><br />
    <%= image_tag photo.file_name %>
    </p>
    <div>
        <% if photo.comments.count > 0 %>
            <strong> Comments: </strong><br />
        <% end %>
        <% photo.comments.each do |comment| %>
            <p>
                <%= link_to comment.user.first_name + " "+comment.user.last_name, user_path(comment.user) %> : 
                <%= comment.comment %>
                <br/>
                <i> Posted <%= comment.date_time %>
                </i>
            </p>
        <% end %>
        <% if session[:login].nil? %>
            <div> <%= link_to 'Log in', login_users_path %> to post comments. </div>
        <% else %>
            <% if posting.nil? %>
                <%= link_to 'Post a comment', new_photo_comment_path(photo) %>
            <% end %>
        <% end %>
    </div>
</div>

project5/app/views/users/index.html.erb
<h1> Listing users </h1>

<table>
    <tr>
        <th>User name</th>
    </tr>
    
    <% @users.each do |user| %>
        <tr>
            <td><%= link_to user.first_name + " " + user.last_name, user_path(user) %></td>
        </tr>
    <% end %>
</table>

project5/app/views/users/login.html.erb
<div>
    <h1>Log in here</h1>
    <div><%= link_to 'Register', new_user_path %></div>
    <% unless session[:login_error].nil? %>
        <% if session[:login_error] == "!password" %>
            <div id="error explanation"><p> Incorrect password. </p></div>
        <% else %>
            <div id="error explanation"><p> No user with login '<%=session[:login_error]%>' was found. </p></div>
        <% end %>
    <% end %>
    <div><%= form_tag(:action => 'post_login') do %>
        <div><p>Login: <%= text_field_tag(:login) %></p></div>
        <div><p>Password: <%= password_field_tag(:password) %></p></div>
        <div><%= submit_tag 'Login' %></div>
    <% end %></div>
</div>

<div><%= link_to 'Back', users_path %></div>

project5/app/views/users/new.html.erb
<div><h1>New User Registration</h1></div>
<div>
    <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
        <div id="error explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prevented user registration:</h2>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li> <%= msg %></li>
            <% end %>
            </ul>
        </div>
        <% end %>
        <p>
            <%= f.label :first_name %><br/>
            <%= f.text_field :first_name %>
        </p>
        <p>
            <%= f.label :last_name %><br/>
            <%= f.text_field :last_name %>
        </p>
        <p>
            <%= f.label :login %><br/>
            <%= f.text_field :login %>
        </p>
        <p>
            <%= f.label :password %><br/>
            <%= f.text_field :password %>
        </p>        
        <p>
            <%= f.submit %>
        </p>
    <% end %>
</div>

project5/app/views/users/post_login.html.erb
<div>
Logged in as <%= session[:login] %>.
</div>

<div><%= link_to 'Back', users_path %></div>

project5/app/views/users/show.html.erb
<h2><%= @user.first_name + " "+@user.last_name %></h2>

<% @user.photos.each do |photo| %>
    <%= render(:partial => "shared/photo_and_comments", :locals=>{:photo => photo,:posting=> nil}) %>
<% end %>

<hr />
<div><%= link_to 'Back', users_path %></div>